CREATE TABLE patients (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    family VARCHAR(255) NOT NULL,
    given VARCHAR(255) NOT NULL,
    dob DATE NOT NULL,
    age INT,
    sex VARCHAR(10) NOT NULL,
    address VARCHAR(255) DEFAULT '',
    phone VARCHAR(20) DEFAULT ''
);