version: '3'
services:
  sql:
    image: mysql:5.7
    container_name: patient-db
    volumes:
      - /data/sql:/src/resources/sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: patientapi
    ports:
      - "3307:3306"
  mongodb:
    image: mongo
    container_name: notes-db
    volumes:
      - /data/mongodb:/data/db
    restart: always
    ports:
      - "27017:27017"
  patient:
    build: ./patient
    container_name: patient
    ports:
      - "8081:8081"
    depends_on:
      - sql
    environment:
      - spring.datasource.url=jdbc:mysql://patient-db:3306/patientapi
    restart: always
  notes:
    build: ./notes
    container_name: notes
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - spring.data.mongodb.uri=mongodb://notes-db:27017/notesapi
  assessment:
    build: ./assessment
    container_name: assessment
    ports:
      - "8080:8080"
    environment:
      - url.patient=patient:8081/patient
      - url.notes=notes:8082/patHistory
  front:
    build: front-bad
    container_name: front
    ports:
      - "8083:8083"
    environment:
      - url.patient=patient:8081/patient
      - url.note=notes:8082/patHistory
      - url.assessment=assessment:8080/assess
